### ISSUE TITLE
dose socks-server support connection log ?

### ISSUE THREAD

**Issue by Qbuer** [clue/php-socks-server#8]
when i using the blacklist feature,   i cant connect to the domain,although i had added the target domain into the whitelist. i try to find out the reason, but i don't know where is the log?

**Comment by clue** [comment]
I'm not sure I follow what kind of "blacklist feature" you're referring to, are you sure this the right repository? Can you provide a gist that highlights the problem you're seeing?

**Comment by Qbuer** [comment]
I use the code provided  in '/examples/server-advanced-outgoing/server-outgoing-blacklist.php' 

$connector->addConnectionManagerFor($permit, '*.hitwh.edu.cn');

And this permit rule doesn't work ('ERR_CONNECTION_REFUSED' shows in chrome) while other work proper. I use 'proxifier' at  client side.

**Comment by clue** [comment]
Thanks! I've just updated the examples with #9 as they used outdated APIs which made this somewhat more complicated than it nowadays has to be :)

I hope this helps :+1: Otherwise, let me know and we can re-open and look into this.
